#include "./nodes.h"

// Define all the nodes with their port uplinks
// clang-format off
node_t nodes[NUM_NODES] = {
    // Center core node
    {NODE_TYPE_CORE, 1, NODE_STATUS_ONLINE, NODE_LOCK_UNLOCKED, {{NODE_PORT_CONNECTED, 2}, {NODE_PORT_CONNECTED, 3}, {NODE_PORT_CONNECTED, 4}, {NODE_PORT_CONNECTED, 5}, {NODE_PORT_CONNECTED, 6}, {NODE_PORT_CONNECTED, 7}}},

    // Ring 1 nodes
    {NODE_TYPE_RING, 2, NODE_STATUS_ONLINE, NODE_LOCK_UNLOCKED, {{NODE_PORT_CONNECTED, 1}, {NODE_PORT_CONNECTED, 3}, {NODE_PORT_CONNECTED, 7}, {NODE_PORT_CONNECTED,  8}, {NODE_PORT_CONNECTED,  9}, {NODE_PORT_CONNECTED, 19}}},
    {NODE_TYPE_RING, 3, NODE_STATUS_ONLINE, NODE_LOCK_UNLOCKED, {{NODE_PORT_CONNECTED, 1}, {NODE_PORT_CONNECTED, 2}, {NODE_PORT_CONNECTED, 4}, {NODE_PORT_CONNECTED,  9}, {NODE_PORT_CONNECTED, 10}, {NODE_PORT_CONNECTED, 11}}},
    {NODE_TYPE_RING, 4, NODE_STATUS_ONLINE, NODE_LOCK_UNLOCKED, {{NODE_PORT_CONNECTED, 1}, {NODE_PORT_CONNECTED, 3}, {NODE_PORT_CONNECTED, 5}, {NODE_PORT_CONNECTED, 11}, {NODE_PORT_CONNECTED, 12}, {NODE_PORT_CONNECTED, 13}}},
    {NODE_TYPE_RING, 5, NODE_STATUS_ONLINE, NODE_LOCK_UNLOCKED, {{NODE_PORT_CONNECTED, 1}, {NODE_PORT_CONNECTED, 4}, {NODE_PORT_CONNECTED, 6}, {NODE_PORT_CONNECTED, 13}, {NODE_PORT_CONNECTED, 14}, {NODE_PORT_CONNECTED, 15}}},
    {NODE_TYPE_RING, 6, NODE_STATUS_ONLINE, NODE_LOCK_UNLOCKED, {{NODE_PORT_CONNECTED, 1}, {NODE_PORT_CONNECTED, 5}, {NODE_PORT_CONNECTED, 7}, {NODE_PORT_CONNECTED, 15}, {NODE_PORT_CONNECTED, 16}, {NODE_PORT_CONNECTED, 17}}},
    {NODE_TYPE_RING, 7, NODE_STATUS_ONLINE, NODE_LOCK_UNLOCKED, {{NODE_PORT_CONNECTED, 1}, {NODE_PORT_CONNECTED, 2}, {NODE_PORT_CONNECTED, 6}, {NODE_PORT_CONNECTED, 17}, {NODE_PORT_CONNECTED, 18}, {NODE_PORT_CONNECTED, 19}}},

    // Ring 2 nodes
    {NODE_TYPE_RING, 8,  NODE_STATUS_ONLINE, NODE_LOCK_UNLOCKED, {{NODE_PORT_CONNECTED, 2}, {NODE_PORT_CONNECTED,  9}, {NODE_PORT_CONNECTED, 19}, {NODE_PORT_CONNECTED, 20}, {NODE_PORT_CONNECTED, 21}, {NODE_PORT_CONNECTED,   26}}},
    {NODE_TYPE_RING, 9,  NODE_STATUS_ONLINE, NODE_LOCK_UNLOCKED, {{NODE_PORT_CONNECTED, 2}, {NODE_PORT_CONNECTED,  3}, {NODE_PORT_CONNECTED,  8}, {NODE_PORT_CONNECTED, 10}, {NODE_PORT_CONNECTED, 21}, {NODE_PORT_UNAVAILABLE,  0}}},
    {NODE_TYPE_RING, 10, NODE_STATUS_ONLINE, NODE_LOCK_UNLOCKED, {{NODE_PORT_CONNECTED, 3}, {NODE_PORT_CONNECTED,  9}, {NODE_PORT_CONNECTED, 11}, {NODE_PORT_CONNECTED, 21}, {NODE_PORT_CONNECTED, 22}, {NODE_PORT_UNAVAILABLE, 27}}},
    {NODE_TYPE_RING, 11, NODE_STATUS_ONLINE, NODE_LOCK_UNLOCKED, {{NODE_PORT_CONNECTED, 3}, {NODE_PORT_CONNECTED,  4}, {NODE_PORT_CONNECTED, 10}, {NODE_PORT_CONNECTED, 12}, {NODE_PORT_CONNECTED, 22}, {NODE_PORT_UNAVAILABLE,  0}}},
    {NODE_TYPE_RING, 12, NODE_STATUS_ONLINE, NODE_LOCK_UNLOCKED, {{NODE_PORT_CONNECTED, 4}, {NODE_PORT_CONNECTED, 11}, {NODE_PORT_CONNECTED, 13}, {NODE_PORT_CONNECTED, 22}, {NODE_PORT_CONNECTED, 23}, {NODE_PORT_CONNECTED,   28}}},
    {NODE_TYPE_RING, 13, NODE_STATUS_ONLINE, NODE_LOCK_UNLOCKED, {{NODE_PORT_CONNECTED, 4}, {NODE_PORT_CONNECTED,  5}, {NODE_PORT_CONNECTED, 12}, {NODE_PORT_CONNECTED, 14}, {NODE_PORT_CONNECTED, 23}, {NODE_PORT_UNAVAILABLE,  0}}},
    {NODE_TYPE_RING, 14, NODE_STATUS_ONLINE, NODE_LOCK_UNLOCKED, {{NODE_PORT_CONNECTED, 5}, {NODE_PORT_CONNECTED, 13}, {NODE_PORT_CONNECTED, 15}, {NODE_PORT_CONNECTED, 23}, {NODE_PORT_CONNECTED, 24}, {NODE_PORT_CONNECTED,   29}}},
    {NODE_TYPE_RING, 15, NODE_STATUS_ONLINE, NODE_LOCK_UNLOCKED, {{NODE_PORT_CONNECTED, 5}, {NODE_PORT_CONNECTED,  6}, {NODE_PORT_CONNECTED, 14}, {NODE_PORT_CONNECTED, 16}, {NODE_PORT_CONNECTED, 24}, {NODE_PORT_UNAVAILABLE,  0}}},
    {NODE_TYPE_RING, 16, NODE_STATUS_ONLINE, NODE_LOCK_UNLOCKED, {{NODE_PORT_CONNECTED, 6}, {NODE_PORT_CONNECTED, 15}, {NODE_PORT_CONNECTED, 17}, {NODE_PORT_CONNECTED, 24}, {NODE_PORT_CONNECTED, 25}, {NODE_PORT_CONNECTED,   30}}},
    {NODE_TYPE_RING, 17, NODE_STATUS_ONLINE, NODE_LOCK_UNLOCKED, {{NODE_PORT_CONNECTED, 6}, {NODE_PORT_CONNECTED,  7}, {NODE_PORT_CONNECTED, 16}, {NODE_PORT_CONNECTED, 18}, {NODE_PORT_CONNECTED, 25}, {NODE_PORT_UNAVAILABLE,  0}}},
    {NODE_TYPE_RING, 18, NODE_STATUS_ONLINE, NODE_LOCK_UNLOCKED, {{NODE_PORT_CONNECTED, 7}, {NODE_PORT_CONNECTED, 17}, {NODE_PORT_CONNECTED, 19}, {NODE_PORT_CONNECTED, 20}, {NODE_PORT_CONNECTED, 25}, {NODE_PORT_CONNECTED,   31}}},
    {NODE_TYPE_RING, 19, NODE_STATUS_ONLINE, NODE_LOCK_UNLOCKED, {{NODE_PORT_CONNECTED, 2}, {NODE_PORT_CONNECTED,  7}, {NODE_PORT_CONNECTED,  8}, {NODE_PORT_CONNECTED, 18}, {NODE_PORT_CONNECTED, 20}, {NODE_PORT_UNAVAILABLE,  0}}},

    // Faction HQ nodes
    {NODE_TYPE_HQ, 20, NODE_STATUS_ONLINE, NODE_LOCK_UNLOCKED, {{NODE_PORT_CONNECTED,  8}, {NODE_PORT_CONNECTED, 18}, {NODE_PORT_CONNECTED, 19}, {NODE_PORT_UNAVAILABLE, 0}, {NODE_PORT_UNAVAILABLE, 0}, {NODE_PORT_UNAVAILABLE, 0}}},
    {NODE_TYPE_HQ, 21, NODE_STATUS_ONLINE, NODE_LOCK_UNLOCKED, {{NODE_PORT_CONNECTED,  8}, {NODE_PORT_CONNECTED,  9}, {NODE_PORT_CONNECTED, 10}, {NODE_PORT_UNAVAILABLE, 0}, {NODE_PORT_UNAVAILABLE, 0}, {NODE_PORT_UNAVAILABLE, 0}}},
    {NODE_TYPE_HQ, 22, NODE_STATUS_ONLINE, NODE_LOCK_UNLOCKED, {{NODE_PORT_CONNECTED, 10}, {NODE_PORT_CONNECTED, 11}, {NODE_PORT_CONNECTED, 12}, {NODE_PORT_UNAVAILABLE, 0}, {NODE_PORT_UNAVAILABLE, 0}, {NODE_PORT_UNAVAILABLE, 0}}},
    {NODE_TYPE_HQ, 23, NODE_STATUS_ONLINE, NODE_LOCK_UNLOCKED, {{NODE_PORT_CONNECTED, 12}, {NODE_PORT_CONNECTED, 13}, {NODE_PORT_CONNECTED, 14}, {NODE_PORT_UNAVAILABLE, 0}, {NODE_PORT_UNAVAILABLE, 0}, {NODE_PORT_UNAVAILABLE, 0}}},
    {NODE_TYPE_HQ, 24, NODE_STATUS_ONLINE, NODE_LOCK_UNLOCKED, {{NODE_PORT_CONNECTED, 14}, {NODE_PORT_CONNECTED, 15}, {NODE_PORT_CONNECTED, 16}, {NODE_PORT_UNAVAILABLE, 0}, {NODE_PORT_UNAVAILABLE, 0}, {NODE_PORT_UNAVAILABLE, 0}}},
    {NODE_TYPE_HQ, 25, NODE_STATUS_ONLINE, NODE_LOCK_UNLOCKED, {{NODE_PORT_CONNECTED, 16}, {NODE_PORT_CONNECTED, 17}, {NODE_PORT_CONNECTED, 18}, {NODE_PORT_UNAVAILABLE, 0}, {NODE_PORT_UNAVAILABLE, 0}, {NODE_PORT_UNAVAILABLE, 0}}},

    // Tower nodes
    {NODE_TYPE_TOWER, 26, NODE_STATUS_ONLINE, NODE_LOCK_UNLOCKED, {{NODE_PORT_CONNECTED,  8}, {NODE_PORT_UNAVAILABLE, 0}, {NODE_PORT_UNAVAILABLE, 0}, {NODE_PORT_UNAVAILABLE, 0}, {NODE_PORT_UNAVAILABLE, 0}, {NODE_PORT_UNAVAILABLE, 0}}},
    {NODE_TYPE_TOWER, 27, NODE_STATUS_ONLINE, NODE_LOCK_UNLOCKED, {{NODE_PORT_CONNECTED, 10}, {NODE_PORT_UNAVAILABLE, 0}, {NODE_PORT_UNAVAILABLE, 0}, {NODE_PORT_UNAVAILABLE, 0}, {NODE_PORT_UNAVAILABLE, 0}, {NODE_PORT_UNAVAILABLE, 0}}},
    {NODE_TYPE_TOWER, 28, NODE_STATUS_ONLINE, NODE_LOCK_UNLOCKED, {{NODE_PORT_CONNECTED, 12}, {NODE_PORT_UNAVAILABLE, 0}, {NODE_PORT_UNAVAILABLE, 0}, {NODE_PORT_UNAVAILABLE, 0}, {NODE_PORT_UNAVAILABLE, 0}, {NODE_PORT_UNAVAILABLE, 0}}},
    {NODE_TYPE_TOWER, 29, NODE_STATUS_ONLINE, NODE_LOCK_UNLOCKED, {{NODE_PORT_CONNECTED, 14}, {NODE_PORT_UNAVAILABLE, 0}, {NODE_PORT_UNAVAILABLE, 0}, {NODE_PORT_UNAVAILABLE, 0}, {NODE_PORT_UNAVAILABLE, 0}, {NODE_PORT_UNAVAILABLE, 0}}},
    {NODE_TYPE_TOWER, 30, NODE_STATUS_ONLINE, NODE_LOCK_UNLOCKED, {{NODE_PORT_CONNECTED, 16}, {NODE_PORT_UNAVAILABLE, 0}, {NODE_PORT_UNAVAILABLE, 0}, {NODE_PORT_UNAVAILABLE, 0}, {NODE_PORT_UNAVAILABLE, 0}, {NODE_PORT_UNAVAILABLE, 0}}},
    {NODE_TYPE_TOWER, 31, NODE_STATUS_ONLINE, NODE_LOCK_UNLOCKED, {{NODE_PORT_CONNECTED, 18}, {NODE_PORT_UNAVAILABLE, 0}, {NODE_PORT_UNAVAILABLE, 0}, {NODE_PORT_UNAVAILABLE, 0}, {NODE_PORT_UNAVAILABLE, 0}, {NODE_PORT_UNAVAILABLE, 0}}},
};
// clang-format on
